spring:
  application:
    name: consortium-datasource-service
  datasource:
    url: jdbc:h2:mem:datasource-consortium
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto:create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true